### ISSUE TITLE
jekyll _config.yml is missing.

### ISSUE THREAD

**Issue by benkay86** [rcifw/rcifw.github.io#12]
The repository does not include the files generated by `jekyll new` (e.g. `_config.yml`) needed to generate a jekyll site from the documentation.  Consequently, testing the jekyll site locally fails:

```
$ ./run_local.sh 
Could not locate Gemfile
Could not locate Gemfile or .bundle/ directory
[benjamin@francesca rcifw.github.io]$ 
```

**Comment by rcifadmin** [comment]
You will need to enter the "docs/" directory (the config is in `docs/_config.yml`) then execute:
`bundle install && bundle exec jekyll serve`

**Comment by rcifadmin** [comment]
The config file is in the repo [here](https://github.com/rcifw/rcifw.github.io/blob/main/docs/_config.yml)

**Comment by benkay86** [comment]
Thank you!  I should have done:

```
cd docs
../run_local.sh
```
