### ISSUE TITLE
update documentation of partitions

### ISSUE THREAD

**Issue by benkay86** [rcifw/rcifw.github.io#22]
Please update the [Partitions and Quality of Service section in `slurm-basics.md`](https://rcifw.github.io/getting-started/slurm-basics.html#partitions-and-quality-of-service) to reflect the new partitions introduced by the upgrade 10/3/2023.

**Comment by rcifadmin** [comment]
Fixed in https://github.com/rcifw/rcifw.github.io/pull/30
